#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB02B1CDFA2F82257 (nick@ilm.com)
#
Name     : compat-ilmbase-soname23
Version  : 2.2.1
Release  : 7
URL      : http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz
Source0  : http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz
Source1 : http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz.sig
Summary  : Base math and exception libraries
Group    : Development/Tools
License  : BSD-3-Clause
Requires: compat-ilmbase-soname23-lib = %{version}-%{release}
Requires: compat-ilmbase-soname23-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress generation of debuginfo
%global debug_package %{nil}

%description
ABOUT THE ILMBASE LIBRARIES
----------------------------
Half is a class that encapsulates our 16-bit floating-point format.

%package lib
Summary: lib components for the compat-ilmbase-soname23 package.
Group: Libraries
Requires: compat-ilmbase-soname23-license = %{version}-%{release}

%description lib
lib components for the compat-ilmbase-soname23 package.


%package license
Summary: license components for the compat-ilmbase-soname23 package.
Group: Default

%description license
license components for the compat-ilmbase-soname23 package.


%prep
%setup -q -n ilmbase-2.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567811885
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1567811885
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-ilmbase-soname23
cp COPYING %{buildroot}/usr/share/package-licenses/compat-ilmbase-soname23/COPYING
cp LICENSE %{buildroot}/usr/share/package-licenses/compat-ilmbase-soname23/LICENSE
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/include/OpenEXR/Iex.h
rm -f %{buildroot}/usr/include/OpenEXR/IexBaseExc.h
rm -f %{buildroot}/usr/include/OpenEXR/IexErrnoExc.h
rm -f %{buildroot}/usr/include/OpenEXR/IexExport.h
rm -f %{buildroot}/usr/include/OpenEXR/IexForward.h
rm -f %{buildroot}/usr/include/OpenEXR/IexMacros.h
rm -f %{buildroot}/usr/include/OpenEXR/IexMathExc.h
rm -f %{buildroot}/usr/include/OpenEXR/IexMathFloatExc.h
rm -f %{buildroot}/usr/include/OpenEXR/IexMathFpu.h
rm -f %{buildroot}/usr/include/OpenEXR/IexMathIeeeExc.h
rm -f %{buildroot}/usr/include/OpenEXR/IexNamespace.h
rm -f %{buildroot}/usr/include/OpenEXR/IexThrowErrnoExc.h
rm -f %{buildroot}/usr/include/OpenEXR/IlmBaseConfig.h
rm -f %{buildroot}/usr/include/OpenEXR/IlmThread.h
rm -f %{buildroot}/usr/include/OpenEXR/IlmThreadExport.h
rm -f %{buildroot}/usr/include/OpenEXR/IlmThreadForward.h
rm -f %{buildroot}/usr/include/OpenEXR/IlmThreadMutex.h
rm -f %{buildroot}/usr/include/OpenEXR/IlmThreadNamespace.h
rm -f %{buildroot}/usr/include/OpenEXR/IlmThreadPool.h
rm -f %{buildroot}/usr/include/OpenEXR/IlmThreadSemaphore.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathBox.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathBoxAlgo.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathColor.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathColorAlgo.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathEuler.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathExc.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathExport.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathForward.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathFrame.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathFrustum.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathFrustumTest.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathFun.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathGL.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathGLU.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathHalfLimits.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathInt64.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathInterval.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathLimits.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathLine.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathLineAlgo.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathMath.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathMatrix.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathMatrixAlgo.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathNamespace.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathPlane.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathPlatform.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathQuat.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathRandom.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathRoots.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathShear.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathSphere.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathVec.h
rm -f %{buildroot}/usr/include/OpenEXR/ImathVecAlgo.h
rm -f %{buildroot}/usr/include/OpenEXR/half.h
rm -f %{buildroot}/usr/include/OpenEXR/halfExport.h
rm -f %{buildroot}/usr/include/OpenEXR/halfFunction.h
rm -f %{buildroot}/usr/include/OpenEXR/halfLimits.h
rm -f %{buildroot}/usr/lib64/libHalf.so
rm -f %{buildroot}/usr/lib64/libIex.so
rm -f %{buildroot}/usr/lib64/libIexMath.so
rm -f %{buildroot}/usr/lib64/libIlmThread.so
rm -f %{buildroot}/usr/lib64/libImath.so
rm -f %{buildroot}/usr/lib64/pkgconfig/IlmBase.pc

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libHalf.so.23
/usr/lib64/libHalf.so.23.0.0
/usr/lib64/libIex-2_2.so.23
/usr/lib64/libIex-2_2.so.23.0.0
/usr/lib64/libIexMath-2_2.so.23
/usr/lib64/libIexMath-2_2.so.23.0.0
/usr/lib64/libIlmThread-2_2.so.23
/usr/lib64/libIlmThread-2_2.so.23.0.0
/usr/lib64/libImath-2_2.so.23
/usr/lib64/libImath-2_2.so.23.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-ilmbase-soname23/COPYING
/usr/share/package-licenses/compat-ilmbase-soname23/LICENSE
